-- Setup database Supabase untuk aplikasi event.
-- Jalankan seluruh file ini di Supabase Dashboard > SQL Editor pada project baru.
--
-- PERINGATAN KEAMANAN:
-- Aplikasi saat ini memakai NEXT_PUBLIC_SUPABASE_ANON_KEY untuk operasi admin.
-- Policy di bawah mengizinkan akses publik agar fitur yang ada berfungsi, sehingga
-- pengunjung dapat membaca/mengubah data tamu dan mengelola file. Tambahkan autentikasi
-- admin dan batasi policy sebelum memakai aplikasi dengan data produksi.

begin;

create table if not exists public.tamu (
  id bigint generated by default as identity primary key,
  nama text not null,
  slug text unique,
  rsvp text,
  komentar text,
  hadir boolean not null default false,
  nama_perusahaan text,
  no_hp text,
  email text,
  no_meja text,
  created_at timestamptz not null default now(),
  waktu_hadir timestamptz
);

create index if not exists tamu_created_at_idx
  on public.tamu (created_at desc);

create index if not exists tamu_slug_idx
  on public.tamu (slug);

create table if not exists public.acara_settings (
  id integer primary key,
  buku_saku_url text,
  agenda_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint acara_settings_singleton check (id = 1)
);

insert into public.acara_settings (id)
values (1)
on conflict (id) do nothing;

create table if not exists public.materi (
  id bigint generated by default as identity primary key,
  judul text not null,
  deskripsi text,
  file_url text not null,
  urutan integer default 1,
  created_at timestamptz not null default now()
);

create index if not exists materi_urutan_idx
  on public.materi (urutan);

alter table public.tamu enable row level security;
alter table public.acara_settings enable row level security;
alter table public.materi enable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on table
  public.tamu,
  public.acara_settings,
  public.materi
  to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

drop policy if exists "Public access tamu" on public.tamu;
create policy "Public access tamu"
  on public.tamu
  for all
  to anon, authenticated
  using (true)
  with check (true);

drop policy if exists "Public access acara_settings" on public.acara_settings;
create policy "Public access acara_settings"
  on public.acara_settings
  for all
  to anon, authenticated
  using (true)
  with check (true);

drop policy if exists "Public access materi" on public.materi;
create policy "Public access materi"
  on public.materi
  for all
  to anon, authenticated
  using (true)
  with check (true);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'dokumen-acara',
  'dokumen-acara',
  true,
  52428800,
  array['application/pdf']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public read dokumen acara" on storage.objects;
create policy "Public read dokumen acara"
  on storage.objects
  for select
  to anon, authenticated
  using (bucket_id = 'dokumen-acara');

drop policy if exists "Public upload dokumen acara" on storage.objects;
create policy "Public upload dokumen acara"
  on storage.objects
  for insert
  to anon, authenticated
  with check (bucket_id = 'dokumen-acara');

drop policy if exists "Public update dokumen acara" on storage.objects;
create policy "Public update dokumen acara"
  on storage.objects
  for update
  to anon, authenticated
  using (bucket_id = 'dokumen-acara')
  with check (bucket_id = 'dokumen-acara');

drop policy if exists "Public delete dokumen acara" on storage.objects;
create policy "Public delete dokumen acara"
  on storage.objects
  for delete
  to anon, authenticated
  using (bucket_id = 'dokumen-acara');

commit;
